# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LookHeart 100' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LookHeart 100

pod 'DGCharts'
pod "TinyConstraints"
pod 'SnapKit'
pod 'Then'
pod 'Alamofire', '~> 5.4'
pod 'Toast-Swift', '~> 5.0.1'
pod 'CryptoSwift'
pod 'KeychainSwift'
pod 'Firebase/Messaging'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
