# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LookHeart 100' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LookHeart 100

pod 'KeychainSwift'
pod 'Firebase/Messaging'

end
